import { enumeration, type Enumeration } from '@reharik/smart-enum';
import { ErrorCategory } from './graphqlSmartEnums';

const errorAreaInput = [
  'album',
  'mediaItem',
  'comment',
  'membership',
  'viewer',
  'auth',
  'authorization',
  'user',
  'reaction',
  'notification',
] as const;

export type ErrorArea = Enumeration<typeof ErrorArea>;
export const ErrorArea = enumeration<typeof errorAreaInput>('ErrorArea', {
  input: errorAreaInput,
});
// @blocksort asc
const contractErrorInput = {
  AddMediaToAlbumEmptyMediaList: {
    code: 'ALBUM_ADD_MEDIA_EMPTY_MEDIA_LIST',
    display: 'At least one media item is required',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  AddMediaToAlbumInvalidTarget: {
    code: 'ALBUM_ADD_MEDIA_INVALID_TARGET',
    display: 'Provide either an existing album or a new album, not both and not neither',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  AlbumNotFound: {
    code: 'ALBUM_NOT_FOUND',
    display: 'Album not found',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  InvalidAlbumItemOrder: {
    code: 'ALBUM_INVALID_ITEM_ORDER',
    display: 'Album item order is invalid',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  AlbumEditCoverForbidden: {
    code: 'ALBUM_EDIT_COVER_FORBIDDEN',
    display: 'Album edit cover forbidden',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  AlbumViewForbidden: {
    code: 'ALBUM_VIEW_FORBIDDEN',
    display: 'Album view forbidden',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  AssetKindAlreadyExists: {
    code: 'ASSET_KIND_ALREADY_EXISTS',
    display: 'Asset kind already exists',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  AssetNotFound: {
    code: 'ASSET_NOT_FOUND',
    display: 'Asset not found',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  AssetNotPending: {
    code: 'ASSET_NOT_PENDING',
    display: 'Asset is not pending',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  CoverMediaNotPartOfAlbum: {
    code: 'ALBUM_COVER_MEDIA_NOT_PART_OF_ALBUM',
    display: 'Cover media not part of album',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  DeleteAlbumItemsNoItemIds: {
    code: 'ALBUM_DELETE_ITEMS_NO_IDS',
    display: 'At least one album item is required to remove',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  DeleteMediaItemsEmptyList: {
    code: 'MEDIA_ITEM_DELETE_ITEMS_EMPTY_LIST',
    display: 'At least one media item is required to delete',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },

  InvalidMediaDimensions: {
    code: 'MEDIA_ITEM_INVALID_DIMENSIONS',
    display: 'Media dimensions must be positive integers',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  InvalidMediaTakenAt: {
    code: 'MEDIA_ITEM_INVALID_TAKEN_AT',
    display: 'Taken at is not a valid date/time',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  InvalidMediaItemTags: {
    code: 'MEDIA_ITEM_INVALID_TAGS',
    display: 'Media item tags are invalid',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MediaAlreadyInAlbum: {
    code: 'ALBUM_MEDIA_ALREADY_IN_ALBUM',
    display: 'Media already in album',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  MediaBytesNotFound: {
    code: 'MEDIA_BYTES_NOT_FOUND',
    display: 'Media bytes not found',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MediaDimensionsNotAvailable: {
    code: 'MEDIA_DIMENSIONS_NOT_AVAILABLE',
    display: 'Could not read media width and height from the uploaded file',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: true,
  },
  MediaItemNotFound: {
    code: 'MEDIA_ITEM_NOT_FOUND',
    display: 'Media item not found',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MediaItemsNotFound: {
    code: 'MEDIA_ITEMS_NOT_FOUND',
    display: 'Media items not found',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MediaItemNotInAlbum: {
    code: 'MEDIA_ITEM_NOT_IN_ALBUM',
    display: 'Media item not in album',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  MediaItemNotOwnedByViewer: {
    code: 'MEDIA_ITEM_NOT_OWNED_BY_VIEWER',
    display: 'Media item not owned by viewer',
    category: ErrorCategory.auth,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MediaItemUpdateNoFieldsProvided: {
    code: 'MEDIA_ITEM_UPDATE_NO_FIELDS_PROVIDED',
    display: 'No fields provided to update',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MediaItemNotReady: {
    code: 'MEDIA_ITEM_NOT_READY',
    display: 'Media item not ready',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MemberNotAllowedToAddItems: {
    code: 'MEMBER_NOT_ALLOWED_TO_ADD_ITEMS',
    display: 'Member not allowed to add items',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  MemberNotAllowedToDeleteAlbum: {
    code: 'MEMBER_NOT_ALLOWED_TO_DELETE_ALBUM',
    display: 'Member not allowed to delete album',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },

  MemberNotAllowedToEditAlbum: {
    code: 'MEMBER_NOT_ALLOWED_TO_EDIT_ALBUM',
    display: 'Member not allowed to edit album',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  NotAllowedToGrantAuthorizationForAlbum: {
    code: 'NOT_ALLOWED_TO_GRANT_AUTHORIZATION_FOR_ALBUM',
    display: 'Not allowed to grant authorization for album',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  NotAllowedToGrantAuthorizationForMediaItem: {
    code: 'NOT_ALLOWED_TO_GRANT_AUTHORIZATION_FOR_MEDIA_ITEM',
    display: 'Not allowed to grant authorization for media item',
    category: ErrorCategory.auth,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MemberNotAllowedToDownloadItems: {
    code: 'MEMBER_NOT_ALLOWED_TO_DOWNLOAD_ITEMS',
    display: 'Member not allowed to download items',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  MemberNotAllowedToComment: {
    code: 'MEMBER_NOT_ALLOWED_TO_COMMENT',
    display: 'Member not allowed to comment',
    category: ErrorCategory.auth,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  StatusNotPending: {
    code: 'MEDIA_ITEM_STATUS_NOT_PENDING',
    display: 'Media item status is not pending',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  StatusNotUploaded: {
    code: 'MEDIA_ITEM_STATUS_NOT_UPLOADED',
    display: 'Media item is not awaiting derivative processing',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  UserAlreadyMember: {
    code: 'ALBUM_USER_ALREADY_MEMBER',
    display: 'User already member',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  UserCanNotCreateAlbum: {
    code: 'USER_CAN_NOT_CREATE_ALBUM',
    display: 'User can not create album',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  UserIsNotMember: {
    code: 'USER_IS_NOT_MEMBER',
    display: 'User is not member',
    category: ErrorCategory.auth,
    area: ErrorArea.album,
    retryable: false,
  },
  MediaItemNotAuthorized: {
    code: 'MEDIA_ITEM_NOT_AUTHORIZED',
    display: 'Media item not authorized',
    category: ErrorCategory.auth,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  InvalidMediaAssetKind: {
    code: 'INVALID_MEDIA_ASSET_KIND',
    display: 'Invalid media variant',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  CanNotGrantAuthorizationToOwner: {
    code: 'CAN_NOT_GRANT_SHARE_TO_OWNER',
    display: 'Cannot grant authorization to owner',
    category: ErrorCategory.auth,
    area: ErrorArea.authorization,
    retryable: false,
  },
  ExpireDateCannotBeInPast: {
    code: 'EXPIRE_DATE_CANNOT_BE_IN_PAST',
    display: 'Expire date cannot be in past, revoke instead',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  CannotUpdateExpiredDateIfRevoked: {
    code: 'CANNOT_UPDATE_EXPIRED_DATE_IF_REVOKED',
    display: 'Cannot update expire date if revoked',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  CannotRevokeAuthorizationIfAlreadyExpired: {
    code: 'CANNOT_REVOKE_SHARE_IF_ALREADY_EXPIRED',
    display: 'Cannot revoke authorization if already expired',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  AuthorizationNotFound: {
    code: 'SHARE_NOT_FOUND',
    display: 'Authorization not found',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  AuthorizationMustHaveGrantedToUserIdOrPublicLinkId: {
    code: 'SHARE_MUST_HAVE_GRANTED_TO_USER_ID_OR_PUBLIC_LINK_ID',
    display: 'Authorization must have granted to user id or public link id',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  AuthorizationMustNotHaveGrantedToUserIdAndPublicLinkId: {
    code: 'SHARE_MUST_NOT_HAVE_GRANTED_TO_USER_ID_AND_PUBLIC_LINK_ID',
    display: 'Authorization must not have granted to user id and public link id at the same time',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  UserNotFound: {
    code: 'USER_NOT_FOUND',
    display: 'User not found',
    category: ErrorCategory.domain,
    area: ErrorArea.user,
    retryable: false,
  },
  NoActionProvidedOnAuthorizationCommand: {
    code: 'NO_ACTION_PROVIDED_ON_AUTHORIZATION_COMMAND',
    display: 'No action provided on authorization command',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  NoActionProvidedOnPublicLinkCommand: {
    code: 'NO_ACTION_PROVIDED_ON_PUBLIC_LINK_COMMAND',
    display: 'No action provided on public link command',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  PublicLinkMustHaveTokenOrId: {
    code: 'PUBLIC_LINK_MUST_HAVE_TOKEN_OR_ID',
    display: 'Public link must have token or id',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  PublicLinkNotFound: {
    code: 'PUBLIC_LINK_NOT_FOUND',
    display: 'Public link not found',
    category: ErrorCategory.domain,
    area: ErrorArea.authorization,
    retryable: false,
  },
  ReplyDepthExceeded: {
    code: 'REPLY_DEPTH_EXCEEDED',
    display: 'Reply depth exceeded',
    category: ErrorCategory.domain,
    area: ErrorArea.comment,
    retryable: false,
  },
  CommentNotFound: {
    code: 'COMMENT_NOT_FOUND',
    display: 'Comment not found',
    category: ErrorCategory.domain,
    area: ErrorArea.comment,
    retryable: false,
  },
  CanNotDeleteComment: {
    code: 'CAN_NOT_DELETE_COMMENT',
    display: 'Can not delete comment',
    category: ErrorCategory.auth,
    area: ErrorArea.comment,
    retryable: false,
  },

  ReactionTargetNotFound: {
    code: 'REACTION_TARGET_NOT_FOUND',
    display: 'Reaction target not found',
    category: ErrorCategory.domain,
    area: ErrorArea.reaction,
    retryable: false,
  },
  ReactionNotAuthorized: {
    code: 'REACTION_NOT_AUTHORIZED',
    display: 'Not authorized to react',
    category: ErrorCategory.auth,
    area: ErrorArea.reaction,
    retryable: false,
  },
  ReactionNotFound: {
    code: 'REACTION_NOT_FOUND',
    display: 'Reaction not found',
    category: ErrorCategory.domain,
    area: ErrorArea.reaction,
    retryable: false,
  },
  NotAllowedToDeleteMediaItem: {
    code: 'NOT_ALLOWED_TO_DELETE_MEDIA_ITEM',
    display: 'Not allowed to delete media item',
    category: ErrorCategory.auth,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  NotAllowedToEditMediaItem: {
    code: 'NOT_ALLOWED_TO_EDIT_MEDIA_ITEM',
    display: 'Not allowed to edit media item',
    category: ErrorCategory.auth,
    area: ErrorArea.mediaItem,
    retryable: false,
  },

  EmailNotConfigured: {
    code: 'EMAIL_NOT_CONFIGURED',
    display: 'Email is not configured',
    category: ErrorCategory.system,
    area: ErrorArea.notification,
    retryable: false,
  },
  EmailSendFailed: {
    code: 'EMAIL_SEND_FAILED',
    display: 'Failed to send email',
    category: ErrorCategory.network,
    area: ErrorArea.notification,
    retryable: true,
  },
  SmsNotConfigured: {
    code: 'SMS_NOT_CONFIGURED',
    display: 'SMS is not configured',
    category: ErrorCategory.system,
    area: ErrorArea.notification,
    retryable: false,
  },
  noNotificationChannelsAvailable: {
    code: 'NO_NOTIFICATION_CHANNELS_AVAILABLE',
    display: 'No notification channels available',
    category: ErrorCategory.domain,
    area: ErrorArea.notification,
    retryable: false,
  },
  noRecipientsProvided: {
    code: 'NO_RECIPIENTS_PROVIDED',
    display: 'No recipients provided',
    category: ErrorCategory.domain,
    area: ErrorArea.notification,
    retryable: false,
  },
  TooManyAttempts: {
    code: 'TOO_MANY_ATTEMPTS',
    display: 'Too many attempts',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  InvalidEmailVerificationCode: {
    code: 'INVALID_EMAIL_VERIFICATION_CODE',
    display: 'Invalid email verification code',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  InvalidPhoneNumber: {
    code: 'INVALID_PHONE_NUMBER',
    display: 'Invalid phone number',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  ErrorActivatingUser: {
    code: 'ERROR_ACTIVATING_USER',
    display: 'Error activating user',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  PartialShareFailure: {
    code: 'PARTIAL_SHARE_FAILURE',
    display: 'Partial share failure',
    category: ErrorCategory.domain,
    area: ErrorArea.user,
    retryable: false,
  },
  PartialAlbumMemberCreation: {
    code: 'PARTIAL_ALBUM_MEMBER_CREATION',
    display: 'Partial album member creation',
    category: ErrorCategory.domain,
    area: ErrorArea.user,
    retryable: false,
  },
  PartialAlbumMemberRemoval: {
    code: 'PARTIAL_ALBUM_MEMBER_REMOVAL',
    display: 'Partial album member removal',
    category: ErrorCategory.domain,
    area: ErrorArea.user,
    retryable: false,
  },
  UserAlreadyExists: {
    code: 'USER_ALREADY_EXISTS',
    display: 'User already exists',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  InvalidEmail: {
    code: 'INVALID_EMAIL',
    display: 'Invalid email',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  MissingFirstOrLastName: {
    code: 'MISSING_FIRST_OR_LAST_NAME',
    display: 'missing first or last name',
    category: ErrorCategory.domain,
    area: ErrorArea.user,
    retryable: false,
  },
  CanOnlyRemoveOwnedItemsOrItemsInAnAlbumYouManage: {
    code: 'CAN_ONLY_REMOVE_OWNED_ITEMS_OR_ITEMS_IN_AN_ALBUM_YOU_MANAGE',
    display: 'You can only remove items you own or items in an album you manage',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  noAuthorizationFoundForId: {
    code: 'NO_AUTHORIZATION_FOUND_FOR_ID',
    display: 'no authorization found for id',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  MemberNotAllowedToAddNewMembers: {
    code: 'MEMBER_NOT_ALLOWED_TO_ADD_NEW_MEMBERS',
    display: 'Member not allowed to add new members',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  MemberNotAllowedToRemoveMembers: {
    code: 'MEMBER_NOT_ALLOWED_TO_REMOVE_MEMBERS',
    display: 'Member not allowed to remove members',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  CanNotRemoveOwnerOfAlbum: {
    code: 'CAN_NOT_REMOVE_OWNER_OF_ALBUM',
    display: 'Can not remove owner of album',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  CanNotRemoveYourselfFromAlbum: {
    code: 'CAN_NOT_REMOVE_YOURSELF_FROM_ALBUM',
    display: 'Can not remove yourself from album',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  CanNotAddMoreThanOneAlbumOwner: {
    code: 'CAN_NOT_ADD_MORE_THAN_ONE_ALBUM_OWNER',
    display: 'Can not add more than one album owner',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  UserDoesNotExist: {
    code: 'USER_DOES_NOT_EXIST',
    display: 'User does not exist',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  UserIsNotActive: {
    code: 'USER_IS_NOT_ACTIVE',
    display: 'User is not active',
    category: ErrorCategory.domain,
    area: ErrorArea.auth,
    retryable: false,
  },
  TooManyRecipients: {
    code: 'TOO_MANY_RECIPIENTS',
    display: 'Too many recipients',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  unknown: {
    code: 'UNKNOWN',
    display: 'Something went wrong',
    category: ErrorCategory.system,
    area: ErrorArea.auth,
    retryable: false,
  },
  CanNotUpdateOwnerOfAlbum: {
    code: 'CAN_NOT_UPDATE_OWNER_OF_ALBUM',
    display: 'Can not update owner of album',
    category: ErrorCategory.domain,
    area: ErrorArea.album,
    retryable: false,
  },
  AssetNotProcessing: {
    code: 'ASSET_NOT_PROCESSING',
    display: 'Asset not processing',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
  MediaItemNotProcessing: {
    code: 'MEDIA_ITEM_NOT_PROCESSING',
    display: 'Media item not processing',
    category: ErrorCategory.domain,
    area: ErrorArea.mediaItem,
    retryable: false,
  },
} as const;
export type ContractError = Enumeration<typeof ContractError>;
export const ContractError = enumeration<typeof contractErrorInput>('ContractError', {
  input: contractErrorInput,
});
