mutation CreatePublicLinkForAlbum($input: CreatePublicLinkForAlbumInput!) {
  createPublicLinkForAlbum(input: $input) {
    data {
      token
    }
    errors {
      ...errorsFragment
    }
  }
}

mutation CreatePublicLinkForMediaItems($input: CreatePublicLinkForMediaItemsInput!) {
  createPublicLinkForMediaItems(input: $input) {
    data {
      token
    }
    errors {
      ...errorsFragment
    }
  }
}

mutation RevokePublicLinkAuthentication($input: RevokePublicLinkAuthenticationInput!) {
  RevokePublicLinkAuthentication(input: $input) {
    data {
      token
    }
    errors {
      ...errorsFragment
    }
  }
}
