mutation grantUserAuthorizationsForMediaItems($input: GrantUserAuthorizationsForMediaItemsInput!) {
  grantUserAuthorizationsForMediaItems(input: $input) {
    data {
      userIds
    }
    errors {
      ...errorsFragment
    }
  }
}

mutation GrantUserAuthorizationForAlbum($input: GrantUserAuthorizationForAlbumInput!) {
  grantUserAuthorizationForAlbum(input: $input) {
    data {
      succeeded {
        email
      }
      failed {
        email
        error {
          code
        }
      }
    }
    errors {
      ...errorsFragment
    }
  }
}

mutation DeleteShareContact($handle: String!) {
  deleteShareContact(handle: $handle) {
    data {
      handle
    }
    errors {
      ...errorsFragment
    }
  }
}

mutation RevokeShareAuthentication($input: RevokeShareAuthenticationInput!) {
  RevokeShareAuthentication(input: $input) {
    data {
      albumId
    }
    errors {
      ...errorsFragment
    }
  }
}
