type Mutation {
  createAlbum(input: CreateAlbumInput!): CreateAlbumResponse!
  AddMediaItemsToAlbum(input: AddMediaItemsToAlbumInput!): AddMediaItemsToAlbumResponse!
  ReorderAlbumItems(input: ReorderAlbumItemsInput!): ReorderAlbumItemsResponse!

  AddAlbumMembers(input: AddAlbumMembersInput!): AddAlbumMembersResponse!
  RemoveAlbumMembers(input: RemoveAlbumMembersInput!): RemoveAlbumMembersResponse!
  RevokeShareAuthentication(
    input: RevokeShareAuthenticationInput!
  ): RevokeShareAuthenticationResponse!
  RevokePublicLinkAuthentication(
    input: RevokePublicLinkAuthenticationInput!
  ): RevokePublicLinkAuthenticationResponse!
  DeleteAlbumItemsFromAlbum(
    input: DeleteAlbumItemsFromAlbumInput!
  ): DeleteAlbumItemsFromAlbumResponse!
  SetCoverMedia(input: SetCoverMediaInput!): SetCoverMediaResponse!
  UnsetCoverMedia(input: UnsetCoverMediaInput!): UnsetCoverMediaResponse!
  grantUserAuthorizationForAlbum(
    input: GrantUserAuthorizationForAlbumInput!
  ): GrantUserAuthorizationResult!

  UpdateAlbumMemberRole(input: UpdateAlbumMemberRoleInput!): UpdateAlbumMemberRoleResponse!
}

input UpdateAlbumMemberRoleInput {
  albumId: ID!
  albumMemberId: ID!
  role: AlbumMemberRole!
}

type UpdateAlbumMemberRoleResponse {
  data: UpdateAlbumMemberRolePayload
  errors: [ContractError!]
}

type UpdateAlbumMemberRolePayload {
  albumMemberId: ID!
  role: AlbumMemberRole!
}

input RevokeShareAuthenticationInput {
  albumId: ID!
  authorizationId: ID!
}

type RevokeShareAuthenticationResponse {
  data: RevokeShareAuthenticationPayload
  errors: [ContractError!]
}

type RevokeShareAuthenticationPayload {
  albumId: ID!
}

input RevokePublicLinkAuthenticationInput {
  albumId: ID!
}

type RevokePublicLinkAuthenticationResponse {
  data: RevokePublicLinkAuthenticationPayload
  errors: [ContractError!]
}

type RevokePublicLinkAuthenticationPayload {
  token: String!
}

input SetCoverMediaInput {
  albumId: ID!
  albumItemId: ID!
}

input UnsetCoverMediaInput {
  albumId: ID!
}
type SetCoverMediaResponse {
  data: SetCoverMediaPayload
  errors: [ContractError!]
}

type SetCoverMediaPayload {
  albumId: ID!
}

type UnsetCoverMediaResponse {
  data: UnsetCoverMediaPayload
  errors: [ContractError!]
}

type UnsetCoverMediaPayload {
  albumId: ID!
}
type CreateAlbumResponse {
  data: CreateAlbumPayload
  errors: [ContractError!]
}

type CreateAlbumPayload {
  albumId: ID!
}

input CreateAlbumInput {
  title: String!
  description: String
}

type AddMediaItemToAlbumResponse {
  data: AddMediaItemToAlbumPayload
  errors: [ContractError!]
}

type AddMediaItemToAlbumPayload {
  albumId: ID!
  albumItemId: ID!
}

input AddMediaItemToAlbumInput {
  albumId: ID!
  mediaItemId: ID!
}

input NewAlbumInAddMediaItemsInput {
  title: String!
  description: String
}

input AddMediaItemsToAlbumInput {
  mediaItemIds: [ID!]!
  albumId: ID
  newAlbum: NewAlbumInAddMediaItemsInput
}

type AddMediaItemsToAlbumResponse {
  data: AddMediaItemsToAlbumPayload
  errors: [ContractError!]
}

type AddMediaItemsToAlbumPayload {
  albumId: ID!
  albumItemIds: [ID!]!
}

input AddAlbumMembersInput {
  userIds: [ID!]!
  role: AlbumMemberRole!
  albumId: ID!
}

type AddAlbumMembersResponse {
  data: AddAlbumMembersPayload
  errors: [ContractError!]
}

type AddAlbumMembersPayload {
  albumId: ID!
  albumMemberIds: [ID!]!
}

input RemoveAlbumMembersInput {
  albumMemberIds: [ID!]!
  albumId: ID!
}

type RemoveAlbumMembersResponse {
  data: RemoveAlbumMembersPayload
  errors: [ContractError!]
}

type RemoveAlbumMembersPayload {
  albumId: ID!
  albumMemberIds: [ID!]!
}

input ReorderAlbumItemsInput {
  albumId: ID!
  albumItemIds: [ID!]!
}

type ReorderAlbumItemsResponse {
  data: ReorderAlbumItemsPayload
  errors: [ContractError!]
}

type ReorderAlbumItemsPayload {
  albumId: ID!
}

type DeleteAlbumItemsFromAlbumResponse {
  data: DeleteAlbumItemsFromAlbumPayload
  errors: [ContractError!]
}
type DeleteAlbumItemsFromAlbumPayload {
  albumId: ID!
  albumItemIds: [ID!]!
}

input DeleteAlbumItemsFromAlbumInput {
  albumId: ID!
  albumItemIds: [ID!]!
}
input GrantUserAuthorizationForAlbumInput {
  albumId: ID!
  grantedToHandles: [String!]!
  label: String
}
